name: Merged Pull Requests Metrics

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  pulls-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: AbarnaaSree
          template: classic
          base: ""
          plugin_pulls: yes
          plugin_pulls_limit: 6
          filename: metrics.pulls.svg
          config_timezone: Asia/Kolkata
